---
title: 'DATA605: Fundamentals of Computational Mathematics'
author: "Donald Butler"
date: "05/07/2022"
output:
  pdf_document:
    extra_dependencies:
    - geometry
    - multicol
    - multirow
  word_document: default
subtitle: Assignment 12
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Taylor Series

$$f(x) = \sum_{n=0}^{\infty}\frac{f^{n}(0)}{n!}x^n$$

We can calculate the Taylor Series expansion by evaluating the first several derivatives of $f(x)$ to identify a pattern for the n-th derivative.

## Problem 1

$$f(x)=\frac{1}{(1-x)}$$

Evaluating the first few derivatives, we can determine a general rule for the n-th derivative.

$\begin{aligned}
f(x) & = \frac{1}{1-x} & \Rightarrow f(0) & = 1 \\
f'(x) & = (1-x)^{-2} & \Rightarrow f'(0) & = 1 \\
f''(x) & = 2(1-x)^{-3} & \Rightarrow f''(0) & = 2 \\
f'''(x) & = 6(1-x)^{-4} & \Rightarrow f'''(0) & = 6 \\
f^{(n)}(x) & = n!(1-x)^{-(n+1)} & \Rightarrow f^{(n)}(0) & = n!
\end{aligned}$

This allows us to generalize the series to:

$$\frac{1}{(1-x)}=\sum_{n=0}^{\infty}x^n$$

The series clearly diverges when $|x|>=1$, so the interval of convergence is $(-1,1)$.

## Problem 2

$$f(x)=e^x$$

Evaluating the first few derivatives, we can determine a general rule for the n-th derivative.

$\begin{aligned}
f(x) & = e^x & \Rightarrow f(0) & = 1 \\
f'(x) & = e^x & \Rightarrow f'(0) & = 1 \\
f''(x) & = e^x & \Rightarrow f''(0) & = 1 \\
f'''(x) & = e^x & \Rightarrow f'''(0) & = 1 \\
f^{(n)}(x) & = e^x & \Rightarrow f^{(n)}(0) & = 1
\end{aligned}$

This allows us to generalize the series to:

$$e^x=\sum_{n=0}^{\infty}\frac{x^n}{n!}$$

Using the ratio test to determine the interval of convergence for the series.

$\begin{aligned}
\lim_{n\to\infty}|\frac{x^{n+1}}{(n+1)!}|/|\frac{x^{n}}{n!}| & = |\frac{x}{n+1}| \\ 
& = \frac{1}{n+1}|x| \\ 
& = 0|x|
\end{aligned}$

The series will converge for all values of $x$.

## Problem 3

$$f(x)=\ln(1+x)$$

Evaluating the first few derivatives, we can determine a general rule for the n-th derivative.

$\begin{aligned}
f(x) & = \ln(1+x) & \Rightarrow f(0) & = 0 \\
f'(x) & = (1+x)^{-1} & \Rightarrow f'(0) & = 1 \\
f''(x) & = -1(1+x)^{-2} & \Rightarrow f''(0) & = -1 \\
f'''(x) & = -2(1+x)^{-3} & \Rightarrow f'''(0) & = -2 \\
f^{(n)}(x) & = (-1)^n(n-1)!(1+x)^{-n} & \Rightarrow f^{(n)}(0) & = (-1)^n(n-1)!
\end{aligned}$

This allows us to generalize the series to:

$$\ln(1+x)=\sum_{n=1}^{\infty}\frac{(-x)^n}{n}$$

Using the ratio test to determine the interval of convergence for the series.

$\begin{aligned}
\lim_{n\to\infty}|\frac{(-x)^{n+1}}{(n+1)}|/|\frac{(-x)^{n}}{n}| & = |\frac{(-x)n}{n+1}| \\ 
& = \frac{n}{n+1}|x| \\ 
& = 1|x|
\end{aligned}$

The ratio test requires that $|x| < 1$ for the series to converge.

## Problem 4

$$f(x)=x^{(1/2)}$$

The function $f(x) = \sqrt{x}$ is not differentiable at $x=0$ because the function is not defined for values of $x < 0$. 