---
title: 'DATA605: Fundamentals of Computational Mathematics'
author: "Donald Butler"
date: "05/07/2022"
output:
  pdf_document:
    extra_dependencies:
    - geometry
    - multicol
    - multirow
  word_document: default
subtitle: Assignment 13
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Problem 1

Use integration by substitution to solve the integral, $\int 4e^{-7x}dx$.

Let $u = -7x$ and $du = -7dx$. 

$\begin{aligned}
\int 4e^{-7x}dx & = \int \frac{4}{-7}e^{-7x}(-7dx) \\
& = \frac{-4}{7} \int e^udu \\
& = \frac{-4}{7}e^u + C \\ 
& = \frac{-4}{7}e^{-7x} + C
\end{aligned}$


## Problem 2

Biologists are treating a pond contaminated with bacteria. The level of contamination is changing at a rate of $\frac{dN}{dt}=\frac{-3150}{t^4}-220$ bacteria per cubic centimeter per day, where $t$ is the number of days since treatment began. Find a function $N(t)$ to estimate the level of contamination if the level after 1 day was 6530 bacteria per cubic centimeter.

$\begin{aligned}
\frac{dN}{dt} & = \frac{-3150}{t^4}-220 \\
dN & = (\frac{-3150}{t^4}-220)dt \\
\int dN & = \int (\frac{-3150}{t^4}-220)dt \\
N(t) & = \int (\frac{-3150}{t^4}-220)dt \\
& = \frac{-3150}{-3t^3}-220t + C \\
& = \frac{1050}{t^3}-220t + C
\end{aligned}$

Use the initial condition to find the value $C$.

$\begin{aligned}
N(1) & = \frac{1050}{1^3} - 220(1) + C \\
6530 & = 1050 - 220 + C \\
5700 & = C
\end{aligned}$

So, $N(t) = \frac{1050}{t^3} - 220t + 5700$.

## Problem 3

Find the total area of the red rectangles in the figure below, where the equation of the line is $f(x) = 2x-9$.

$\sum_{x=5}^{8} (1)(2x-9) = 1 + 3 + 5 + 7 = 16$

## Problem 4

Find the area of the region bounded by the graphs of the given equations.

$$y = x^2-2x-2, y = x + 2$$

Find the values of x where these equations intersect.

$\begin{aligned}
x + 2 & = x^2 - 2x - 2 \\
0 & = x^2 -3x - 4 \\
0 & = (x-4)(x+1)
\end{aligned}$

Calculate the definite integral on the interval $(-1,4)$.

$\begin{aligned}
\int_{-1}^{4} (x+2) - (x^2-2x-2) dx & = \int_{-1}^4 -x^2 + 3x + 4 dx \\
& = \frac{-x^3}{3} + \frac{3x^2}{2} + 4x \big|_{-1}^4 \\
& = \frac{-64}{3} + \frac{48}{2} + 16 - \frac{1}{3} - \frac{3}{2} + 4 \\
& = 20\frac{5}{6}
\end{aligned}$

## Problem 5

A beauty supply store expects to sell 110 flat irons during the next year. It costs \$3.75 to store one flat iron for one year. There is a fixed cost of \$8.25 for each order. Find the lot size and the number of orders per year that will minimize inventory costs.

Inventory Cost = Holding Cost + Ordering Cost

Assumptions

1. Sales are made at a relatively uniform rate. This allows us to assume that we are on average holding half the lot size over the year.
2. Lot size, $x$, of each reorder is the same.
3. As inventory falls to 0, another order arrives immediately.

$$f(x) = 3.75 \frac{x}{2} + 8.25 \frac{110}{x}$$

To find the minimum value of $f(x)$, we find the value of $x$ to satisfy $f'(x)=0$. 

$\begin{aligned}
f'(x) & = 1.875 - 907.5x^{-2} \\
0 & = 1.875 - 907.5x^{-2} \\
907.5x^{-2} & = 1.875 \\
\frac{907.5}{1.875} & = x^2 \\
484 & = x^2 \\
22 & = x
\end{aligned}$

With a lot size of 22, we can minimize inventory costs by making 5 orders per year.

## Problem 6

Use integration by parts to solve the integral below.

$$\int \ln(9x)x^6 dx$$

Integration by parts: $\int u dv = uv - \int v du$.

Let $u = ln(9x)$ and $dv = x^6dx$. Then $du = \frac{1}{x} dx$ and $v = \frac{x^7}{7}$.

$\begin{aligned}
\int \ln(9x)x^6 dx & = \int u dv \\
& = uv - \int v du \\
& = \frac{ln(9x)x^7}{7} - \int \frac{x^7}{7} * \frac{1}{x} dx \\
& = \frac{ln(9x)x^7}{7} - \int \frac{x^6}{7} dx \\
& = \frac{ln(9x)x^7}{7} - \frac{x^7}{49} + C
\end{aligned}$

## Problem 7

Determine whether $f(x)$ is a probability density function on the interval $[1,e^6]$. If not, determine the value of the definite integral.

$$f(x) = \frac{1}{6x}$$

A probability density function must be greater than or equal to 0 over the interval and the integral over the interval must be equal to 1. The function $f(x)$ is strictly greater than 0 on the interval $[1,e^6]$, which satisfies the first requirement. 

$\begin{aligned}
\int_1^{e^6} f(x) dx & = \int_1^{e^6} \frac{1}{6x} dx \\
& = \frac{1}{6} \int_1^{e^6} \frac{1}{x} dx \\
& = \frac{1}{6} (\ln(e^6) - \ln(1)) \\
& = \frac{1}{6} (6 - 0) \\
& = 1
\end{aligned}$

Since the integral on the interval is 1, the function is a probability density function.
